### ISSUE TITLE
Spring Test with multiple contexts: java.lang.IllegalStateException: Cache already created

### ISSUE THREAD

**Issue by gavvvr** [cache2k/cache2k#123]
Hi. I configure Cache2k bean in my Spring Boot app the same way it is suggested to do in `Programmatic Setup` section of [the documentation](https://cache2k.org/docs/latest/user-guide.html#enable-cache2k-spring-support).
Please see the following question to reproduce the issue:
https://stackoverflow.com/q/57201103/3581539

Since `org.cache2k.CacheManager` is cached for the same classloader (`CacheManager.getInstance()`), in case test suite needs to create another application context (i.e. with a mocked bean), cache initialization fails causing `IllegalStateException` and test failure:

```
java.lang.IllegalStateException: Cache already created: 'cache'
    at org.cache2k.core.CacheManagerImpl.newCache(CacheManagerImpl.java:174)
    at org.cache2k.core.InternalCache2kBuilder.buildAsIs(InternalCache2kBuilder.java:239)
    at org.cache2k.core.InternalCache2kBuilder.build(InternalCache2kBuilder.java:182)
    at org.cache2k.core.Cache2kCoreProviderImpl.createCache(Cache2kCoreProviderImpl.java:215)
    at org.cache2k.Cache2kBuilder.build(Cache2kBuilder.java:837)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.buildAndWrap(SpringCache2kCacheManager.java:205)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.lambda$addCache$2(SpringCache2kCacheManager.java:143)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.addCache(SpringCache2kCacheManager.java:141)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.addCaches(SpringCache2kCacheManager.java:132)
    at com.example.cachingdemo.CachingDemoApplication.springCacheManager(CachingDemoApplication.java:23)
    at com.example.cachingdemo.CachingDemoApplication$$EnhancerBySpringCGLIB$$2dce99ca.CGLIB$springCacheManager$0(<generated>)
    at com.example.cachingdemo.CachingDemoApplication$$EnhancerBySpringCGLIB$$2dce99ca$$FastClassBySpringCGLIB$$bbd240c0.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
    at com.example.cachingdemo.CachingDemoApplication$$EnhancerBySpringCGLIB$$2dce99ca.springCacheManager(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
    ... 52 more
```

How would you suggest to fix the problem? For now i think that I will create cachemanager bean with `@Profile("!testing")` and will enable this profile when tests are running

**Comment by cruftex** [comment]
> Since org.cache2k.CacheManager is cached for the same classloader (CacheManager.getInstance()), in case test suite needs to create another application context (i.e. with a mocked bean), cache initialization fails

The simple configuration you use, assumes one Spring application context that uses the default cache2k cache manager.

For testing with different application contexts, I suggest using a unique cache manager for each context.  I am not a Spring guru, can you check something like:

````
   @Autowired
   private ApplicationContext applicationContext;

    @Bean
    public CacheManager springCacheManager() {
        SpringCache2kCacheManager cacheManager = 
           new SpringCache2kCacheManager("springtesting-" + applicationContext.getId());
        cacheManager.addCaches(b -> b.name("cache"));
        return cacheManager;
    }
````

An alternative would be to actually share the SpringCacheManager between the applications contexts. This may be error prone, but might speed up testing times.

Especially when you create lots of application contexts, there might be a memory leak since the caches / cache managers are never closed. For that kind of setup we should provide a close / shutdown functionality.

There is obviously a misfit since the current code allows to multiple `SpringCache2kCacheManager` instances to be created on top of a single cache2k `CacheManager` instance. I think its best to add a check for that, so you get a meaningful exception earlier on.

**Comment by gavvvr** [comment]
Thank you @cruftex, this worked out:

```
String ctxId = ctx.getId() + Integer.toHexString(ctx.hashCode());
SpringCache2kCacheManager cacheManager = new SpringCache2kCacheManager(ctxId);
```

Looks like an elegant solution for my simple case at the moment.

> Especially when you create lots of application contexts, there might be a memory leak since the caches / cache managers are never closed

My app actually uses single ApplicationContext. Multiple context are created and cached (not disposed) by Spring Test in order to make their execution fast. There are two different contexts in memory at the same time because one of test classes have mocked bean.

> An alternative would be to actually share the SpringCacheManager between the applications contexts.

Not sure if it is possible with Spring Test to have a Parent ctx with single CacheManager, but also sounds like a good idea.

My problem is solved, thank you. An issue can be closed. I created it partly to let you know that with default Spring Context configuration Cache2k is not always friendly with Spring Test.

**Comment by cruftex** [comment]
Thanks for the feedback! Unfortunately `ctx.getId()` and `ctx.getName()` is empty in the testing context, so its not usable to create a unique name. The hash code is a good approach. Using the hash code of the configuration object is even simpler, e.g.: `new SpringCache2kCacheManager("spring-" + hashCode())`

I created a integration test here:
https://github.com/cache2k/cache2k-qa/tree/master/spring-boot-multiple-context-test

Doing a proper shutdown of the cache manager, seems not to give any improvement, since Spring is shutting down both at the very end. But maybe there are other options which control that.

**Comment by cruftex** [comment]
Added a small hint to the documentation.
