### ISSUE TITLE
Graal native image support

### ISSUE THREAD

**Issue by reibitto** [cache2k/cache2k#152]
Does cache2k support Graal native image? I tried it and ran into the following:

```
Exception in thread "main" org.cache2k.CacheException: register JMX bean, ObjectName: org.cache2k:type=CacheManager,name=default
	at org.cache2k.impl.serverSide.JmxSupport.managerCreated(JmxSupport.java:116)
	at org.cache2k.core.CacheManagerImpl.<init>(CacheManagerImpl.java:116)
	at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:160)
	at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:135)
	at org.cache2k.CacheManager.getInstance(CacheManager.java:93)
	at org.cache2k.Cache2kBuilder.config(Cache2kBuilder.java:165)
	at org.cache2k.Cache2kBuilder.disableStatistics(Cache2kBuilder.java:742)
	at commandcenter.command.cache.InMemoryCache$.make(InMemoryCache.scala:26)
	at commandcenter.CCRuntime.runtime(CCRuntime.scala:21)
	at commandcenter.CCRuntime.runtime$(CCRuntime.scala:14)
	at commandcenter.cli.Main$.runtime$lzycompute(Main.scala:12)
	at commandcenter.cli.Main$.runtime(Main.scala:12)
	at commandcenter.CCApp.platform(CCApp.scala:27)
	at commandcenter.CCApp.platform$(CCApp.scala:27)
	at commandcenter.cli.Main$.platform$lzycompute(Main.scala:12)
	at commandcenter.cli.Main$.platform(Main.scala:12)
	at zio.Runtime.unsafeRunAsyncCancelable(Runtime.scala:112)
	at zio.Runtime.unsafeRunAsyncCancelable$(Runtime.scala:105)
	at commandcenter.cli.Main$.unsafeRunAsyncCancelable(Main.scala:12)
	at zio.Runtime.unsafeRunAsync(Runtime.scala:94)
	at zio.Runtime.unsafeRunAsync$(Runtime.scala:93)
	at commandcenter.cli.Main$.unsafeRunAsync(Main.scala:12)
	at zio.Runtime.unsafeRunSync(Runtime.scala:82)
	at zio.Runtime.unsafeRunSync$(Runtime.scala:79)
	at commandcenter.cli.Main$.unsafeRunSync(Main.scala:12)
	at zio.Runtime.unsafeRun(Runtime.scala:59)
	at zio.Runtime.unsafeRun$(Runtime.scala:58)
	at commandcenter.cli.Main$.unsafeRun(Main.scala:12)
	at commandcenter.CCApp.main(CCApp.scala:14)
	at commandcenter.CCApp.main$(CCApp.scala:10)
	at commandcenter.cli.Main$.main(Main.scala:12)
	at commandcenter.cli.Main.main(Main.scala)
Caused by: java.lang.NullPointerException
	at org.cache2k.impl.serverSide.JmxSupport.managerCreated(JmxSupport.java:110)
	... 31 more
```

I'm using cache2k in a Scala project, but I'm pretty sure that's irrelevant.

I'm curious why this JMX error is popping up even if I explicitly set `enableJmx(false)`. I currently only have `cache2k-api` and `cache2k-core` as dependencies. This all works fine with a normal JVM (I'm using JDK 11).

I'm thinking this is an AOT issue with native-image. Dynamic loading and reflection can cause weird behavior for native-image if not specifically worked around. But that's just a guess. Honestly, I have no idea what JMX even is. 😛

I can provide more information if needed, but I was just checking if Graal native-image was considered as a target in the first place.

**Comment by cruftex** [comment]
Thanks for the hint. Although its a remarkable achievement, I did not try out GraalVM yet. I will try it out.
To interpret the stack trace, what version of cache2k did you use?

**Comment by reibitto** [comment]
I'm using 1.2.4.Final but I also tried 1.3.4.Beta and it fails with the same message.

Graal native image issues can be frustrating to solve sometimes. I have experience solving some reflection issues, but I've never seen this JMX one so I'm not sure how much help I'll be. The [GraalVM Gitter](https://gitter.im/graalvm/graal-core) is helpful though.

**Comment by reibitto** [comment]
One other thing that _might_ help is that you can detect if it's a native executable with `System.getProperty("java.vm.name")`. It'll return "Substrate VM". But that's usually something I only use as a last resort if I'm disabling something or taking a different code path at runtime.

Ideally, most things are solved using native-image options or reflection config.

**Comment by cruftex** [comment]
I am trying to create `reflect-config.json`. At the moment I am struggling much more early in startup phase then you.
Now I am getting:

```
Aug 29, 2020 3:43:30 PM org.cache2k.core.Cache2kCoreProviderImpl
INFO: cache2k starting. version=1.3.4.Beta
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:68)
        at org.cache2k.impl.xmlConfiguration.generic.Util.copyViaSerialization(Util.java:39)
        at org.cache2k.impl.xmlConfiguration.CacheConfigurationProviderImpl.getDefaultConfiguration(CacheConfigurationProviderImpl.java:91)
        at org.cache2k.core.Cache2kCoreProviderImpl.getDefaultConfiguration(Cache2kCoreProviderImpl.java:228)
        at org.cache2k.Cache2kBuilder.config(Cache2kBuilder.java:167)
        at org.cache2k.Cache2kBuilder.entryCapacity(Cache2kBuilder.java:354)
        at Main.main(Main.java:8)
```

Serialization is unsupported in Graal: https://github.com/oracle/graal/issues/460

A tiny project with your Graal configuration and the Graal version you are using would be helpful so I can reproduce you problem exactly.

cache2k does not rely on JMX or on the XML configuration part (that uses reflection and serialization). However I am not sure how to remove that in a GraalVM configuration. For Andriod it works via Proguard rules

**Comment by reibitto** [comment]
My config looks like this:
https://github.com/reibitto/command-center/blob/master/build.sbt#L85-L97

I'm using an SBT plugin, but the flags are the same. I'm using `--allow-incomplete-classpath` and `--report-unsupported-elements-at-runtime` for other reasons, but that's temporary and should typically not be used (I had a separate Windows-only issue I was working around).

My project has a lot of extra stuff. I can try creating a small hello world on my side too to see what happens. And to reduce the amount of variables here.

**Comment by cruftex** [comment]
Is it possible for you to remove "org/cache2k/impl" when assembling the complete application?

Thanks for the pointer. I check with your paramaters.

**Comment by reibitto** [comment]
Hmm, I can remove transitive dependencies, but that's not what you're referring to, right? I'm not sure how to remove just "org/cache2k/impl".

**Comment by cruftex** [comment]
> Is it possible for you to remove "org/cache2k/impl" when assembling the complete application?

Unfortunately, that requires changing the META-INF/services files as well. I just hit the error:

```
Error: Could not find registered service implementation class `org.cache2k.impl.serverSide.JmxSupport` for service `org.cache2k.core.spi.CacheLifeCycleListener`
com.oracle.svm.core.util.UserError$UserException: Could not find registered service implementation class `org.cache2k.impl.serverSide.JmxSupport` for service `org.cache2k.core.spi.CacheLifeCycleListener`
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:203)
        at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:112)
```

> Hmm, I can remove transitive dependencies, but that's not what you're referring to, right? I'm not sure how to remove just "org/cache2k/impl".

I used the exclude option from the maven shade plugin that I use to create the "Uber jar".

**Comment by cruftex** [comment]
With `--initialize-at-build-time` I get now:

```
Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
```

At least that is the definitive hint that JMX is not supported by GraalVM, which I could not find somewhere else.

I do some changes, that JMX is not initialized during class loading. Will report a bit later.

**Comment by cruftex** [comment]
I just released a new version 1.3.5.Beta which has additional switches to disable JMX and XML configuration completely.
The native image needs to be build with `--initialize-at-build-time` and this parameters:

````
-Dorg.cache2k.impl.serverSide.JmxSupport.Tunable.enable=off
-Dorg.cache2k.core.Cache2kCoreProviderImpl.Tunable.enableExternalConfiguration=off
````

BTW: 1.3.5.Beta will probably not get much changes any more and this will be 1.4.0.Final.

To improve things further I see the following options:
- For the XML configuration we can wait things out and hope Graal will get serialization support. Other projects are affected by that as well
- Change the configuration code to not rely on serialization
- We could detect Graal and disable XML configuration and JMX in that environment by default
- Alternatively move XML confuration and JMX out of the `cache2k-core` jar and make it optional rather than relying on different mechanisms to get rid of it again. I think I had this separation in 1.0 but got complaints about too many jars.

**Comment by reibitto** [comment]
Thanks! That was quick. I'm perfectly fine with using the beta version.

I'm still struggling a bit with the new version though. I'm definitely farther along this time though. A few things I found:

- I was using GraalVM 20.1.0 and this was causing problems. But that's fine. Upgrading to GraalVM 20.2.0 solved that. Apparently they changed the initialization strategy between these two versions, so stuff like that is probably expected. I guess using the latest version is pretty important considering a bunch of native-image fixes are always included in new releases.
- After adding both `commons-logging:commons-logging:1.1.3` and `org.slf4j:slf4j-nop:1.7.30` as dependencies the build succeeded (that is if I want to avoid the `--allow-incomplete-classpath` flag).

After those two things and setting the flags you added, the native-image build succeeded. But when I go to run it I get:

```
Exception in thread "main" java.lang.IllegalArgumentException: Not able to instantiate cache implementation
	at org.cache2k.core.InternalCache2kBuilder.constructImplementationAndFillParameters(InternalCache2kBuilder.java:186)
	at org.cache2k.core.InternalCache2kBuilder.buildAsIs(InternalCache2kBuilder.java:217)
	at org.cache2k.core.InternalCache2kBuilder.build(InternalCache2kBuilder.java:192)
	at org.cache2k.core.Cache2kCoreProviderImpl.createCache(Cache2kCoreProviderImpl.java:224)
	at org.cache2k.Cache2kBuilder.build(Cache2kBuilder.java:914)
	at scratch.Main$.main(Main.scala:10)
	at scratch.Main.main(Main.scala)
Caused by: java.lang.InstantiationException: Type `org.cache2k.core.HeapCache` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:850)
	at org.cache2k.core.InternalCache2kBuilder.constructImplementationAndFillParameters(InternalCache2kBuilder.java:184)
	... 6 more
```

I feel like this is close now, but I'm not sure what's missing here.

**Comment by reibitto** [comment]
I likely need to tweak the reflection config settings. Let me try a few things.

**Comment by reibitto** [comment]
Yeah, that was it. I got my example project to work by also adding this to my reflection config:

```json
{
  "name": "org.cache2k.core.HeapCache",
  "allDeclaredConstructors": true,
  "allPublicConstructors": true,
  "allDeclaredMethods": true,
  "allPublicMethods": true,
  "allDeclaredClasses": true,
  "allPublicClasses": true
},
{
  "name": "org.cache2k.core.concurrency.OptimisticLockStamped",
  "allDeclaredConstructors": true,
  "allPublicConstructors": true,
  "allDeclaredMethods": true,
  "allPublicMethods": true,
  "allDeclaredClasses": true,
  "allPublicClasses": true
}
```

I can now work on trying to integrate cache2k into my original project. I'm having GraalVM 20.2.0 issues there, but that's almost certainly unrelated to cache2k.

**Comment by cruftex** [comment]
Okay, cool. Thanks for the feedback. I will do some tests and try to ship the reflection configuration in the cache2k jar file so things work OOTB.

**Comment by reibitto** [comment]
There might be more reflection config needed depending on what execution paths you hit. This is just what was required for my test.

There's the `native-image-agent` you can set in the `-agentlib` option which can automatically generate it, but I don't have much experience with using that. I think for that tool the more execution paths you hit, the better.

**Comment by cruftex** [comment]
Just release version 1.3.6.Beta, with improved GraalVM support.
In short, no extra configuration is needed any more.

Changes in detail:

- Added native-image.properties that enables build time initialization where neccessary
- Removed reflection usage at runtime, reflection is only used during build time
- Moved initialization of log into a static initializer. The log implementation to use is detected during build time.
  This avoids `--allow-incomplete-classpath` or the logging jar files to be present
- Made more values constant to improve ability for code optimization
- Disabled JMX and XML configuration when GraalVM native image is build. 
  A GraalVM native image build is detected by the presence of the system property `org.graalvm.nativeimage.kind`.
  
Tested with GraalVM 20.2.0.

Here is a test project that checks whether all cache2k functions are available:
https://github.com/cache2k/cache2k-qa/tree/master/graalvm-native-image

Any feedback appreciated!

**Comment by reibitto** [comment]
Thanks. Those look like nice changes. I gave it a try just now and I'm seeing an issue though:

```
line 1 column 0 Expected json literal but found /
[error] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
```

I see that the json config has comments in it and that's typically not supported. I believe that's the cause of the error.

**Comment by cruftex** [comment]
Oops. Sorry about that. The headers were added via the maven plugin after I did all the testing locally.
I released just 1.3.7.Beta which fixes the problem. Thanks for the fast test feedback!

**Comment by reibitto** [comment]
That did it. Confirmed it works without any special config. Thanks!

**Comment by cruftex** [comment]
Glad to hear that. Thanks for bringing this to attention.
Closing this issue. Feel free to comment again should there any more issues or questions.
