### ISSUE TITLE
Dead lock

### ISSUE THREAD

**Issue by javalover123** [cache2k/cache2k#194]
Dead lock with 2.8-SNAPSHOT, for example below is 0x00000000ca194e40

`
<pre>
Cache<String, LocalDateTime> TIME_CACHE = new Cache2kBuilder<String, LocalDateTime>() {
    }.refreshAheadPolicy(new AutoRefreshPolicy<>())
            .expireAfterWrite(1, TimeUnit.SECONDS)
            .loader((key) -> LocalDateTime.now())
            .build();
</pre>
`

"ForkJoinPool.commonPool-worker-189" #174 daemon prio=5 os_prio=0 cpu=218.75ms elapsed=211.89s tid=0x000001e58d048000 nid=0x5ac at breakpoint [0x0000007d4bcfe000]
   java.lang.Thread.State: RUNNABLE
	at org.cache2k.core.HeapCache.provideDefaultLoaderExecutor(HeapCache.java:295)
	at org.cache2k.core.HeapCache$LazyLoaderExecutor.execute(HeapCache.java:161)
	- locked <0x00000000ca04fe70> (a java.lang.Object)
	at org.cache2k.core.HeapCache$LazyRefreshExecutor.execute(HeapCache.java:178)
	- locked <0x00000000ca04fe70> (a java.lang.Object)
	at org.cache2k.core.HeapCache.timerEventRefresh(HeapCache.java:1545)
	- locked <0x00000000ca194e40> (a org.cache2k.core.Entry)
	at org.cache2k.core.timing.Tasks$RefreshTimerTask.fire(Tasks.java:77)
	at org.cache2k.core.timing.Tasks.action(Tasks.java:67)
	at org.cache2k.core.timing.DefaultTimer.timeReachedEvent(DefaultTimer.java:186)
	at org.cache2k.core.timing.DefaultTimer.access$100(DefaultTimer.java:43)
	at org.cache2k.core.timing.DefaultTimer$1.run(DefaultTimer.java:69)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@11.0.10/ForkJoinTask.java:1426)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(java.base@11.0.10/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.10/ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.10/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.10/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.10/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.10/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
	- None

"ThreadPoolTaskScheduler-1" #406 prio=5 os_prio=0 cpu=1343.75ms elapsed=200.05s tid=0x000001e59bf3e000 nid=0x5740 waiting for monitor entry  [0x0000007d51afd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.cache2k.core.AccessWrapper.getValueOrException(AccessWrapper.java:79)
	- waiting to lock <0x00000000ca194e40> (a org.cache2k.core.Entry)
	at org.cache2k.core.AccessWrapper.getValue(AccessWrapper.java:65)
	at org.cache2k.core.HeapCache.returnValue(HeapCache.java:1168)
	at org.cache2k.core.CompactEntry.getValue(Entry.java:113)
	at org.cache2k.core.Entry.getValue(Entry.java:163)
	at org.cache2k.core.HeapCache.get(HeapCache.java:516)

   Locked ownable synchronizers:
	- <0x00000000c7ad8370> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by javalover123** [comment]
Maybe caused I am debug and break point at loader, then execute TIME_CACHE.get("")
