### ISSUE TITLE
cache2k-spring module fail when compile with native  

### ISSUE THREAD

**Issue by ashraf-revo** [cache2k/cache2k#199]
we are getting this error when compiling with native 
```
Error: Classes that should be initialized at run time got initialized during image building:
 ch.qos.logback.core.util.StatusPrinter was unintentionally initialized at build time. To see why ch.qos.logback.core.util.StatusPrinter got initialized use --trace-class-initialization=ch.qos.logback.core.util.StatusPrinter
ch.qos.logback.classic.Logger was unintentionally initialized at build time. To see why ch.qos.logback.classic.Logger got initialized use --trace-class-initialization=ch.qos.logback.classic.Logger
ch.qos.logback.classic.Level was unintentionally initialized at build time. To see why ch.qos.logback.classic.Level got initialized use --trace-class-initialization=ch.qos.logback.classic.Level
ch.qos.logback.core.status.StatusBase was unintentionally initialized at build time. To see why ch.qos.logback.core.status.StatusBase got initialized use --trace-class-initialization=ch.qos.logback.core.status.StatusBase
ch.qos.logback.core.util.Loader was unintentionally initialized at build time. To see why ch.qos.logback.core.util.Loader got initialized use --trace-class-initialization=ch.qos.logback.core.util.Loader
ch.qos.logback.core.CoreConstants was unintentionally initialized at build time. To see why ch.qos.logback.core.CoreConstants got initialized use --trace-class-initialization=ch.qos.logback.core.CoreConstants
ch.qos.logback.core.status.InfoStatus was unintentionally initialized at build time. To see why ch.qos.logback.core.status.InfoStatus got initialized use --trace-class-initialization=ch.qos.logback.core.status.InfoStatus
org.slf4j.LoggerFactory was unintentionally initialized at build time. To see why org.slf4j.LoggerFactory got initialized use --trace-class-initialization=org.slf4j.LoggerFactory
To see how the classes got initialized, use --trace-class-initialization=ch.qos.logback.core.util.StatusPrinter,ch.qos.logback.classic.Logger,ch.qos.logback.classic.Level,ch.qos.logback.core.status.StatusBase,ch.qos.logback.core.util.Loader,ch.qos.logback.core.CoreConstants,ch.qos.logback.core.status.InfoStatus,org.slf4j.LoggerFactory
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```
this is  a simple demo that produce this error https://github.com/ashraf-revo/cache-error

**Comment by cruftex** [comment]
Thanks for the bug report and the small project to reproduce it quickly, @ashraf-revo!

There is a stackoverflow article that seems relevant:
https://stackoverflow.com/questions/60654455/how-to-fix-try-avoiding-to-initialize-the-class-that-caused-initialization-wit

I added the trace option and got:
Error: Classes that should be initialized at run time got initialized during image building:

````
 org.slf4j.LoggerFactory was unintentionally initialized at build time. io.netty.channel.AbstractChannel caused initialization of this class with the following trace: 
        at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:94)
        at io.netty.util.internal.logging.Slf4JLoggerFactory.<init>(Slf4JLoggerFactory.java:42)
        at io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder.<clinit>(Slf4JLoggerFactory.java:63)
        at io.netty.util.internal.logging.Slf4JLoggerFactory.getInstanceWithNopCheck(Slf4JLoggerFactory.java:59)
        at io.netty.util.internal.logging.InternalLoggerFactory.useSlf4JLoggerFactory(InternalLoggerFactory.java:62)
        at io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:42)
        at io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:111)
        at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:134)
        at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:127)
        at io.netty.channel.AbstractChannel.<clinit>(AbstractChannel.java:45)
````

So it seems netty is the cause. However, cache2k has code as well that is initializing the logging at build time. I added this, so the binding to the log is done at build time and unused log libraries would be discarded. This worked fine and without complaints in older GraalVM images.

When googling I do find some similar bugs. However, I cannot find any hint what is the actual root cause why `org.slf4j.LoggerFactory` should not be initialized.

It is possible to remove the initialization code from cache2k (its in `org.cache2k.core.log.Log`) but I assume it would not solve the problem since netty is doing it as well.

Maybe the suggestion in the SO article helps?

**Comment by linghengqian** [comment]
- This is the behavior of the Netty-specific GraalVM reachability metadata, and collection of GraalVM reachability metadata for specific Netty modules must be actively terminated. Simple way, like I solved in https://github.com/oracle/graalvm-reachability-metadata/pull/170 by opening the metadataRepository of GraalVM Native Build Tools. https://github.com/oracle/graalvm-reachability-metadata/tree/0.2.5/metadata/io.netty documents the specific behavior of these modules.
- I don't think this is a problem that needs to be handled on the Cache2k side.

**Comment by snicoll** [comment]
@cruftex is there an appetite from the team to provide native support? Ideally it should be in the form of some testing on your side and either built-in metadata or metadata contributed to the [official reachability metadata repo](https://github.com/oracle/graalvm-reachability-metadata). We have a smoke test with Spring and Cache2K that's failing on native and we're considering removing it if this doesn't move. Thanks!

**Comment by cruftex** [comment]
@snicoll Thanks for the ping. I look into it the next days.

**Comment by sdeleuze** [comment]
Those initialization errors could be fixed with recent GraalVM versions (Java 21 and later).

@ashraf-revo Could you try with the latest GraalVM version released and let us know if you still see the error?

**Comment by ashraf-revo** [comment]
sure i will  @sdeleuze

**Comment by ashraf-revo** [comment]
@sdeleuze 
i still getting the same error 

`Error: Unsupported features in 3 methods
Detailed message:
Error: An object of type 'ch.qos.logback.classic.Logger' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.Logger' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.Logger'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.Logger' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.Logger'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.Logger' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$Slf4jLogger.logger of constant 
    org.cache2k.core.log.Log$Slf4jLogger@136b2b30: org.cache2k.core.log.Log$Slf4jLogger@136b2b30
  reading field java.util.HashMap$Node.value of constant 
    java.util.HashMap$Node@980cdec: org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@13...
  indexing into array java.util.HashMap$Node[]@2e2d152: [Ljava.util.HashMap$Node;@2e2d152 at index 13
  reading field java.util.HashMap.table of constant 
    java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1...
  scanning root java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1... embedded in 
    org.cache2k.core.log.Log.getLog(Log.java:64)
  parsing method org.cache2k.core.log.Log.getLog(Log.java:64) reachable via the parsing context
    at org.cache2k.core.CacheManagerImpl.<init>(CacheManagerImpl.java:117)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:139)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:114)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.<init>(SpringCache2kCacheManager.java:93)
    at com.asrevo.cacheerror.CacheErrorApplication.cacheManager(CacheErrorApplication.java:20)
    at com.asrevo.cacheerror.CacheErrorApplication$$SpringCGLIB$$0.cacheManager(<generated>)
    at root method.(Unknown Source)

Error: An object of type 'ch.qos.logback.classic.Logger' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.Logger' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.Logger'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.Logger' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.Logger'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.Logger' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$Slf4jLogger.logger of constant 
    org.cache2k.core.log.Log$Slf4jLogger@32e22c18: org.cache2k.core.log.Log$Slf4jLogger@32e22c18
  reading field java.util.HashMap$Node.value of constant 
    java.util.HashMap$Node@261e257c: org.cache2k.core.log.Log=org.cache2k.core.log.Log$Slf4jLogger@32e22c18
  indexing into array java.util.HashMap$Node[]@2e2d152: [Ljava.util.HashMap$Node;@2e2d152 at index 15
  reading field java.util.HashMap.table of constant 
    java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1...
  scanning root java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1... embedded in 
    org.cache2k.core.log.Log.getLog(Log.java:64)
  parsing method org.cache2k.core.log.Log.getLog(Log.java:64) reachable via the parsing context
    at org.cache2k.core.CacheManagerImpl.<init>(CacheManagerImpl.java:117)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:139)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:114)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.<init>(SpringCache2kCacheManager.java:93)
    at com.asrevo.cacheerror.CacheErrorApplication.cacheManager(CacheErrorApplication.java:20)
    at com.asrevo.cacheerror.CacheErrorApplication$$SpringCGLIB$$0.cacheManager(<generated>)
    at root method.(Unknown Source)

Error: An object of type 'ch.qos.logback.classic.LoggerContext' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.LoggerContext' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.LoggerContext'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.LoggerContext' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.LoggerContext'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.LoggerContext' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$$Lambda/0x0a51f2429e5b26508cb30fa47b8be57247807ad80.arg$1 of constant 
    org.cache2k.core.log.Log$$Lambda/0x0a51f2429e5b26508cb30fa47b8be57247807ad80@292802cf: org.cache2k.core.log.Log$$Lambda/0x000000004873e3e0@292802cf
  reading static field org.cache2k.core.log.Log.LOG_FACTORY
    at <unknown-location>
  registered as read because: null
```
Error: Unsupported features in 3 methods
Detailed message:
Error: An object of type 'ch.qos.logback.classic.Logger' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.Logger' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.Logger'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.Logger' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.Logger'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.Logger' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$Slf4jLogger.logger of constant 
    org.cache2k.core.log.Log$Slf4jLogger@136b2b30: org.cache2k.core.log.Log$Slf4jLogger@136b2b30
  reading field java.util.HashMap$Node.value of constant 
    java.util.HashMap$Node@980cdec: org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@13...
  indexing into array java.util.HashMap$Node[]@2e2d152: [Ljava.util.HashMap$Node;@2e2d152 at index 13
  reading field java.util.HashMap.table of constant 
    java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1...
  scanning root java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1... embedded in 
    org.cache2k.core.log.Log.getLog(Log.java:64)
  parsing method org.cache2k.core.log.Log.getLog(Log.java:64) reachable via the parsing context
    at org.cache2k.core.CacheManagerImpl.<init>(CacheManagerImpl.java:117)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:139)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:114)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.<init>(SpringCache2kCacheManager.java:93)
    at com.asrevo.cacheerror.CacheErrorApplication.cacheManager(CacheErrorApplication.java:20)
    at com.asrevo.cacheerror.CacheErrorApplication$$SpringCGLIB$$0.cacheManager(<generated>)
    at root method.(Unknown Source)

Error: An object of type 'ch.qos.logback.classic.Logger' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.Logger' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.Logger'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.Logger' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.Logger'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.Logger' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$Slf4jLogger.logger of constant 
    org.cache2k.core.log.Log$Slf4jLogger@32e22c18: org.cache2k.core.log.Log$Slf4jLogger@32e22c18
  reading field java.util.HashMap$Node.value of constant 
    java.util.HashMap$Node@261e257c: org.cache2k.core.log.Log=org.cache2k.core.log.Log$Slf4jLogger@32e22c18
  indexing into array java.util.HashMap$Node[]@2e2d152: [Ljava.util.HashMap$Node;@2e2d152 at index 15
  reading field java.util.HashMap.table of constant 
    java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1...
  scanning root java.util.HashMap@637582f: {org.cache2k.core.Cache2kCoreProviderImpl=org.cache2k.core.log.Log$Slf4jLogger@1... embedded in 
    org.cache2k.core.log.Log.getLog(Log.java:64)
  parsing method org.cache2k.core.log.Log.getLog(Log.java:64) reachable via the parsing context
    at org.cache2k.core.CacheManagerImpl.<init>(CacheManagerImpl.java:117)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:139)
    at org.cache2k.core.Cache2kCoreProviderImpl.getManager(Cache2kCoreProviderImpl.java:114)
    at org.cache2k.extra.spring.SpringCache2kCacheManager.<init>(SpringCache2kCacheManager.java:93)
    at com.asrevo.cacheerror.CacheErrorApplication.cacheManager(CacheErrorApplication.java:20)
    at com.asrevo.cacheerror.CacheErrorApplication$$SpringCGLIB$$0.cacheManager(<generated>)
    at root method.(Unknown Source)

Error: An object of type 'ch.qos.logback.classic.LoggerContext' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'ch.qos.logback.classic.LoggerContext' are persisted in the image heap, add 

    '--initialize-at-build-time=ch.qos.logback.classic.LoggerContext'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'ch.qos.logback.classic.LoggerContext' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=ch.qos.logback.classic.LoggerContext'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

If you are seeing this message after upgrading to a new GraalVM release, this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=ch.qos.logback.classic.LoggerContext' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.

The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field org.cache2k.core.log.Log$$Lambda/0x0a51f2429e5b26508cb30fa47b8be57247807ad80.arg$1 of constant 
    org.cache2k.core.log.Log$$Lambda/0x0a51f2429e5b26508cb30fa47b8be57247807ad80@292802cf: org.cache2k.core.log.Log$$Lambda/0x000000004873e3e0@292802cf
  reading static field org.cache2k.core.log.Log.LOG_FACTORY
    at <unknown-location>
  registered as read because: null

```

**Comment by sdeleuze** [comment]
I see [native metadata are included in cache2k-core JAR](https://github.com/cache2k/cache2k/blob/master/cache2k-core/src/main/resources/META-INF/native-image/org.cache2k/cache2k-core/native-image.properties), this is likely the source of this error.

I have not read all the detail on https://github.com/cache2k/cache2k/issues/152, but moving forward there should be no explicit build time initialisation like that because that introduces some by design incompatibilities like the one you see here. All metadata in https://github.com/oracle/graalvm-reachability-metadata don't have such build time init for that reason.

I would suggest you do a new test with the latest version of GraalVM and without this builtin `native-image.propertie`, and I can help you to move forward if that does not work as expected.
