### ISSUE TITLE
Exception in AsyncDispatcher.getLockObject if key.hashCode is negative

### ISSUE THREAD

**Issue by agavrilov** [cache2k/cache2k#55]
I'm using Cache2k 1.0.0.CR2 as JCache provider. If I use an object with a negative hash code as a key, Cache2k throws an ArrayIndexOutOfBoundsException in AsyncDispatcher.getLockObject. Here is the full exception:

```java
java.lang.ArrayIndexOutOfBoundsException: -10
	at org.cache2k.core.event.AsyncDispatcher.getLockObject(AsyncDispatcher.java:55)
	at org.cache2k.core.event.AsyncDispatcher.queue(AsyncDispatcher.java:74)
	at org.cache2k.core.InternalCache2kBuilder$AsyncExpiredListener.onEntryExpired(InternalCache2kBuilder.java:397)
	at org.cache2k.core.WiredCache.callExpiryListeners(WiredCache.java:600)
	at org.cache2k.core.WiredCache.expireOrScheduleFinalExpireEvent(WiredCache.java:593)
	at org.cache2k.core.WiredCache.timerEventExpireEntry(WiredCache.java:582)
	at org.cache2k.core.TimingHandler$ExpireTask.fire(TimingHandler.java:487)
	at org.cache2k.core.TimingHandler$CommonTask.run(TimingHandler.java:470)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

Here is a simple example to reproduce an issue:
```java
    public void cache2k_expirationDurationWithNegativeHashCode() throws Exception {
        final int KEY = -10;
        final int VALUE = 20;

        MutableConfiguration<Integer, Integer> config = ExtendedMutableConfiguration.of(
                        Cache2kBuilder.of(Integer.class, Integer.class)
                                        .entryCapacity(100)
                                        .expireAfterWrite(1, TimeUnit.SECONDS));
        config.setTypes(Integer.class, Integer.class);
        config.setStoreByValue(false);

        CachingProvider cachingProvider = Caching.getCachingProvider();
        CacheManager mgr = cachingProvider.getCacheManager();

        try (Cache<Integer, Integer> cache = mgr.createCache("cache", config)) {

            cache.put(KEY, VALUE);

            Thread.sleep(1500);

            assertEquals(null, cache.get(KEY));
        }
    }

```

**Comment by cruftex** [comment]
Thanks for the report. I can reproduce it and will fix it as soon as possible.

**Comment by cruftex** [comment]
Just release 1.0.0.CR3 with a fix.
