### ISSUE TITLE
Can't create cache (Cache2kConfiguration deserialization)

### ISSUE THREAD

**Issue by dutoitns** [cache2k/cache2k#72]
Hi,

My code works on my local machine but when I deploy the code the cache can't be created.

I get the following error:
```
Caused by: org.cache2k.xmlConfiguration.ConfigurationException: Copying default cache configuration for manager 'default'
	at org.cache2k.xmlConfiguration.CacheConfigurationProviderImpl.copyViaSerialization(CacheConfigurationProviderImpl.java:227)
	at org.cache2k.xmlConfiguration.CacheConfigurationProviderImpl.getDefaultConfiguration(CacheConfigurationProviderImpl.java:76)
	at org.cache2k.core.Cache2kCoreProviderImpl.getDefaultConfiguration(Cache2kCoreProviderImpl.java:215)
	at org.cache2k.Cache2kBuilder.config(Cache2kBuilder.java:156)
	at org.cache2k.Cache2kBuilder.name(Cache2kBuilder.java:306)
	at za.co.shoprite.mediaportal.AWSCommPackage.util.cache.cache2k.AbstractCacheManager.getCache(AbstractCacheManager.java:121)
	... 117 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Deserialization not allowed for class org.cache2k.configuration.Cache2kConfiguration (on Thu Oct 26 09:44:03 UTC 2017)
	at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
	at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:248)
	at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1826)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.cache2k.xmlConfiguration.CacheConfigurationProviderImpl.copyViaSerialization(CacheConfigurationProviderImpl.java:225)
	... 122 common frames omitted
```

My code for creating the cache:
```
this.theCache = new Cache2kBuilder<String, Object>() {}
					.name(getCacheName()) // needs to be unique
				        .expireAfterWrite(6, TimeUnit.HOURS)
					.entryCapacity(2000) // the default, should be sufficient for now
				        .build();
```

Any help or insights appreciated :)

**Comment by dutoitns** [comment]
All sorted.  It was an issue with NotSoSerial (https://github.com/kantega/notsoserial).  I don't know whether it gets packaged with cache2k but I'm assuming for now that it used by the server I'm using (Adobe Experience Manager).  I had to add the org.cache2k.* package to a deserialization firewall within the server's admin interface - and then everything worked :)

**Comment by cruftex** [comment]
Thanks for the bug report and its resolution. Others will find that as well now.

cache2k uses serialization/deserialization internally to make a copy of the configuration object. The NotSoSerial thing is not from cache2k and probably comes with your application server. I will keep that in mind. Next time when I work at that code area I will check whether there is a chance to use another mechanism then serialization.
