### ISSUE TITLE
Proguard Rules for Android

### ISSUE THREAD

**Issue by rodrixan** [cache2k/cache2k#76]
Hi!

Thanks for the project, it's amazing!

Nevertheless, whenever I try to use it in an Android project that also uses Proguard, the compiler says that some classes could not be found:
```
Warning:org.cache2k.core.util.Log: can't find referenced class org.slf4j.LoggerFactory
Warning:org.cache2k.core.util.Log: can't find referenced class org.slf4j.helpers.NOPLoggerFactory
Warning:org.cache2k.core.util.Log: can't find referenced class org.slf4j.LoggerFactory
Warning:org.cache2k.core.util.Log: can't find referenced class org.slf4j.ILoggerFactory
Warning:org.cache2k.core.util.Log$1: can't find referenced class org.slf4j.ILoggerFactory
Warning:org.cache2k.core.util.Log$Slf4jLogger: can't find referenced class org.slf4j.Logger
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ManagementFactory
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadMXBean
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadInfo
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadMXBean
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadInfo
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ManagementFactory
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadMXBean
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadInfo
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadMXBean
Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadInfo

```
I have tried to add the following rules to avoid it:
```
-keep public class org.cache2k.core.util.**
-dontwarn org.slf4j**
-dontwarn java.lang.management**

```
But as soon as I launch the app with the rules, It crash because it can't find some methods (they are obfuscated so it won't call them)

What are the rules that must be used??

Thanks in advice!

**Comment by cruftex** [comment]
Thanks for the report!

> Warning:org.cache2k.core.util.Log: can't find referenced class org.slf4j.LoggerFactory

Yes, that warning must be ignored. If slf4j is not available, the logging falls back to another mechanism.

> Warning:org.cache2k.core.util.ThreadDump: can't find referenced class java.lang.management.ThreadInfo

Interesting, I think that stuff should not be there. I will see whether I can remove it.

> What are the rules that must be used??

I regularly test new versions on Android, but not yet with ProGuard. So I am a little lost here as well.

Some background: There are two jar files `cache2k-api` and `cache2k-core`. The API jar has no dependency on the core jar. So in order to find the implementation there is some magic going on. Actually its a variant of the service loader concept. Since the service loader does not work on Android there is another mechanism (`cache2k-api/SingleProviderResolver`). I am not to happy with that.

Ideas:

Most likely keeping `org.cache2k.core.Cache2kCoreProviderImpl` should be sufficient.

If that does not lead to success, I would keep `org.cache2k` and obfuscate/minimize in `org.cache2k.core` except `org.cache2k.core.Cache2kCoreProviderImpl`

Maybe somebody else has some ProGuard rules?

**Comment by rodrixan** [comment]
Both solutions doesn't seem to work. 

> Most likely keeping org.cache2k.core.Cache2kCoreProviderImpl should be sufficient.

This one keeps crashing the app once it wants to access the cache

> If that does not lead to success, I would keep org.cache2k and obfuscate/minimize in org.cache2k.core except org.cache2k.core.Cache2kCoreProviderImpl

Directly gradle informs that a NullPointerException has occurred while obfuscating

**Comment by rodrixan** [comment]
Ok I have tried the following proguard file

```
-keep public class org.cache2k.**
-keep class org.cache2k.**
-dontwarn org.slf4j**
-dontwarn java.lang.management**
```

And it seems to work, buuut this means that nothing is obfuscated inside the library.

Maybe can be refined with a better set of rules. A little research shows that the only classes that can't be obfuscated are the ones that use reflexion in any way, so It might be the answer...

**Comment by rodrixan** [comment]
Update: 
Now the library is showing this error:

```
                                                                            java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)
                                                                             Caused by: java.lang.NoClassDefFoundError: java.util.concurrent.locks.StampedLock
                                                                                at org.cache2k.core.concurrency.OptimisticLockStamped.<init>(Unknown Source)
                                                                                at java.lang.Class.newInstanceImpl(Native Method)
                                                                                at java.lang.Class.newInstance(Class.java:1208)
                                                                                at org.cache2k.core.concurrency.Locks.newOptimistic(Unknown Source)
                                                                                at org.cache2k.core.Hash2.<init>(Unknown Source)
                                                                                at org.cache2k.core.HeapCache.<init>(Unknown Source)
                                                                                at java.lang.Class.newInstanceImpl(Native Method)
                                                                                at java.lang.Class.newInstance(Class.java:1208)
                                                                                at org.cache2k.core.InternalCache2kBuilder.constructImplementationAndFillParameters(Unknown Source)
                                                                                at org.cache2k.core.InternalCache2kBuilder.buildAsIs(Unknown Source)
                                                                                at org.cache2k.core.InternalCache2kBuilder.build(Unknown Source)
                                                                                at org.cache2k.core.Cache2kCoreProviderImpl.createCache(Unknown Source)
                                                                                at org.cache2k.Cache2kBuilder.build(Unknown Source)
```

**Comment by cruftex** [comment]
This looks very odd. It looks like it is executing a code path that is only intended for Java 8 and above.
Can you tell me your Android version?

**Comment by rodrixan** [comment]
Android version is 4.4.4 and above. It happens in every device I've tried.

Min sdk: 19
Target sdk: 26
Source compatibility: 1.7 (Java 7) - I have also tried to downgrade to 1.6 but the problem still persists >.<

However, if I use the option "dontoptimize" in proguard rules, the crash disappears... It seems the issue is related to the library optimization when proguard does it...

**Comment by cruftex** [comment]
> However, if I use the option "dontoptimize" in proguard rules, the crash disappears... It seems the issue is related to the library optimization when proguard does it...

Interesting.

Cache2k probes for `java.util.concurrent.locks.StampedLock` and uses it when available.
The probing code is in `org.cache2k.core.concurrency.Locks`. Probably proguard finds that it can evaluate the code at compile time. Can you try with excluding `org.cache2k.core.concurrency.Locks` from optimization?

**Comment by rodrixan** [comment]
That's what I'm currently investigating, but for the moment I haven't see nothing about "Avoid optimization for a specific class"

**Comment by cruftex** [comment]
There is a new release (1.1.1.Alpha) which comes with an example of ProGuard rules.
The description is here: https://cache2k.org/docs/latest/user-guide.html#android
The JUnit test is is in the module: https://github.com/cache2k/cache2k/tree/master/test-android-proguard

The versions 1.1.x are intended for development and to stabilize the new features. I plan to release 1.2 in a couple of weeks.
