### ISSUE TITLE
Cache2K with expiration timer + Jersey produces an 'Timer execution exception'

### ISSUE THREAD

**Issue by Neiko2002** [cache2k/cache2k#89]
Hello together,

i'm using cache2k inside a custom factory of Jersey to supply my injections. The factory produces objects based on a HttpServletRequest object. After adding a cache to map from HttpServletRequest to my desired object I get the following exception:

```
2018-08-10 15:52:26,587 o.c.Cache/default:requestToContext - Timer execution exception 
java.lang.IllegalStateException: Not inside a request scope.
	at org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:177)
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:79)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:89)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:125)
	at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:62)
	at com.sun.proxy.$Proxy34.hashCode(Unknown Source)
	at org.cache2k.core.HeapCache.checkForHashCodeChange(HeapCache.java:1334)
	at org.cache2k.core.HeapCache.removeEntry(HeapCache.java:703)
	at org.cache2k.core.HeapCache.expireAndRemoveEventually(HeapCache.java:1658)
	at org.cache2k.core.HeapCache.expireEntry(HeapCache.java:1644)
	at org.cache2k.core.HeapCache.expireOrScheduleFinalExpireEvent(HeapCache.java:1628)
	at org.cache2k.core.HeapCache.timerEventExpireEntry(HeapCache.java:1615)
	at org.cache2k.core.TimingHandler$ExpireTimerTask.fire(TimingHandler.java:517)
	at org.cache2k.core.TimingHandler$CommonTimerTask.run(TimingHandler.java:500)
	at org.cache2k.core.util.SimpleTimer$TimerThread.mainLoop(SimpleTimer.java:389)
	at org.cache2k.core.util.SimpleTimer$TimerThread.run(SimpleTimer.java:337)
```

The cache is build using a loader and expires the elements after 10 seconds.
```
new Cache2kBuilder<HttpServletRequest, MyContext>() {}
	.name("requestToContext")
	.loader(MyContextFactory::createContext)
	.entryCapacity(1000)
	.expireAfterWrite(10, TimeUnit.SECONDS)
	.build();
```

What I don't understand is why the method `org.cache2k.core.HeapCache.expireAndRemoveEventually` calls a remove method which after removing the element checks its HashCode. In my case at the time an element expires the HttpServletRequest object has already been cleaned up by jersey. There is no valid HashCode anymore.

**Comment by cruftex** [comment]
An object used as key needs to be immutable and needs to produce identical hash codes. The rules for key objects are identical to those of the Map interface. Other caches will have trouble with your key as well.

When removing an entry, cache2k checks whether the key is still producing the same hash code. This is a counter measure to detect keys that are mutated. In your case it detects not a key mutation, but that the actual key content is gone.

The `HttpServletRequest` is not ideal for a cache key. It is heavy weight and has a life time bound to the request. The `HttpServletRequest` might get wrapped also. A key should be as compact as possible and uniquely identify the cached resource and immutable. 

Solutions:

For logging purposes we generate a unique request ID per request and hold that as request attribute and as thread local variable. That is a string identifying the request, which would be perfect for a cache key.

The other question is why you need a cache at all, and don't store your context object in the request attribute directly (`HttpServletRequest.setAttribute` / `getAttribute`)

Hope that helps. Happy to discuss this more.
